project:
  type: book
  output-dir: docs
  
book:
  title: Getting Started with R
  repo-url: https://github.com/ottosven/rintro
  repo-actions: [edit, issue]
  downloads: [pdf]
  author: Sven Otto
  sidebar: false
  navbar: false
  date: today
  date-format: "MMMM D, YYYY"
  search: true
  page-navigation: true
  open-graph: true
  chapters:
    - index.qmd
    - baseR.qmd
    - packages.qmd

format:
  pdf:
    include-in-header: preamble-latex.tex
    documentclass: scrreprt
    fig-align: center
  html:
    theme:
      light: [default, theme.scss]
      dark: [default, darkly, theme.scss]
    linkcolor: green
    monofont: Fira Mono
    number-sections: true
    code-link: true
    reference-links: true
    reference-location: margin
    knitr:
      opts_chunk:
        fig.align: center
    fig-align: center
  
resources:
  - CNAME
  - rintro-sec1.R
  - rintro-sec2.R